import './globals.css';
import { Inter, Roboto } from 'next/font/google';
import type { Metadata } from 'next';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className={inter.className}>
        <div className="px-24 py-5 text-3xl font-medium text-red-500 fixed">
          <Link href="/">blog.</Link>
        </div>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
        </main>
      </body>
    </html>
  );
}
